name: ESP32 Arduino Libs CI

on:
  workflow_dispatch:  # Manually start a workflow
  # push:
  #   branches:
  #   - master
  # pull_request:

concurrency:
  group: esp-idf-libs-${{github.event.pull_request.number || github.ref}}
  cancel-in-progress: true

jobs:
  build-libs:
    name: Build Libs for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # target: [esp32, esp32s2, esp32s3, esp32c3]
        target: [esp32]
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: bash ./tools/prepare-ci.sh
    - name: Build Libs for ${{ matrix.target }}
      run: bash ./build.sh -t ${{ matrix.target }}
    - name: Release
      uses: jason2866/action-gh-release@v1.2
      with:
        tag_name: ${{ github.run_number }}
        body_path: release-info.txt
        prerelease: true
        files: |
          dist/framework*
          release-info.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

